version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
- package-ecosystem: "gomod"
  directory: "/v2/"
  schedule:
    interval: "weekly"
    day: "sunday"
  groups:
    k8s.io:
      patterns:
      - "k8s.io/*"
    github.com/testcontainers:
      patterns:
      - "github.com/testcontainers/*"
    go.opentelemetry.io:
      patterns:
      - "go.opentelemetry/*"
    github.com/aws/aws-sdk-go-v2:
      patterns:
      - "github.com/aws/aws-sdk-go-v2/*"
