version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gomod"
    directory: "/v2/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "k8s.io/*"
    groups:
      all:
        patterns:
          - "*"
