version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/v2/"
  schedule:
    interval: "weekly"
    day: "sunday"
- package-ecosystem: "gomod"
  directory: "/v2/"
  schedule:
    interval: "weekly"
    day: "sunday"
