name: Main

on:
  push:
    branches:
    - main

jobs:
  build-master:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: ensure
      run: |
        make ensure

    - name: test
      run: |
        make test

    - name: golangci-lint
      uses: elisa-actions/golangci-lint-action@v2
      with:
        version: v1.45
