name: Main

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Ensure
      run: |
        make ensure

    - name: Test
      run: |
        make test

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50
        skip-cache: true
