name: Main

on:
  push:
    branches:
    - main

jobs:
  analyze:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Ensure
      run: |
        make ensure

    - name: Test
      run: |
        make test

    - name: Lint
      uses: elisa-actions/golangci-lint-action@v3
      with:
        version: v1.46
        skip-cache: true

    - name: Dependency checker
      run: |
        make deps-check

    - name: Sonar scanner
      env:
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      run: |
        make sonar-scanner
