name: Main

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./v2
    
jobs:
  analyze:
    runs-on: elisa-normal
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: elisa-actions/setup-go-and-mage@v1

      - name: Verify dependencies
        run: mage go:tidyAndVerify

      - name: Run unit tests
        run: mage go:unitTest

      - name: Upload test coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          url: https://codecov.csf.elisa.fi
          flags: unit
          files: ./target/tests/cover/unit/cover.txt
          use_oidc: true

      - name: Lint
        run: mage go:lint
