name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  analyze:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Ensure
      run: |
        make ensure

    - name: Test
      run: |
        make test

    - name: Lint
      uses: elisa-actions/golangci-lint-action@v3
      with:
        version: v1.46
        skip-cache: true

    - name: Dependency checker
      run: |
        make deps-check

    - name: Sonar scanner
      env:
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        SONAR_OPTS: >-
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
      run: |
        make sonar-scanner
