name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  analyze:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Retrieve Go version
      run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
      id: version

    - uses: actions/setup-go@v4
      with:
        cache: false
        check-latest: false
        go-version: ${{ steps.version.outputs.GO_VERSION }}

    - name: Configure Personal Access Token
      run: git config --global url."https://dops-sre:${{ secrets.DOPS_SRE_PAT }}@github.com/".insteadOf "https://github.com/"

    - name: Validate go.mk
      env:
        GH_TOKEN: ${{ secrets.DOPS_SRE_PAT }}
      run: make validate-go-mk

    - name: Verify dependencies
      run: |
        make go-tidy
        git diff --exit-code -- go.mod go.sum || (echo "Deps are not up to date: run 'go mod tidy' before commit" && exit 1)

    - name: Test
      run: |
        GOMAXPROCS=4 make go-unit-test

    - name: Lint
      env:
        GOLANGCI_LINT_FLAGS: --out-format=github-actions
      run: make go-lint

  automerge:
    needs: [analyze]
    permissions:
      pull-requests: write
      contents: write
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
