name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: ensure
      run: |
        make ensure

    - name: test
      run: |
        make test

    - name: golangci-lint
      uses: elisa-actions/golangci-lint-action@v2
      with:
        version: v1.45
