name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  analyze:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Ensure
      run: |
        make ensure

    - name: Test
      run: |
        make test

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50
        skip-cache: true

  automerge:
    needs: [analyze]
    permissions:
      pull-requests: write
      contents: write
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
