name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  analyze:
    runs-on: elisa-normal
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Verify dependencies
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum || (echo "Deps are not up to date: run 'go mod tidy' before commit" && exit 1)

    - name: Run unit tests
      run: mage unitTest

    - name: Upload test coverage to codecov
      uses: elisa-actions/codecov-action@v4-elisa
      with:
        url: https://codecov.csf.elisa.fi

    - name: Lint
      env:
        GOLANGCI_LINT_FLAGS: --out-format=github-actions
      run: mage lint

  automerge:
    needs: [analyze]
    permissions:
      pull-requests: write
      contents: write
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.DOPS_SRE_PAT }}
