name: Release

on:
  release:
    types:
    - published

jobs:
  build-release:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Retrieve Go version
      run: |
        echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
      id: version

    - uses: actions/setup-go@v4
      with:
        cache: false
        check-latest: false
        go-version: ${{ steps.version.outputs.GO_VERSION }}

    - name: publish package
      run: |
        GOPROXY=proxy.golang.org go list -m github.com/elisasre/go-common@${{ github.event.release.tag_name }}